
DISCORD_TOKEN = ''
OPENAI_API_KEY = ''
TELEGRAM_API_ID = ''
TELEGRAM_API_HASH = ''
TELEGRAM_CHANNEL_ID = ''
TWITTER_COOKIES = {}

PYTESSERACT_PATH = ''
DISCORD_PATH = ''
DISCORD_TITLE = ''
DISCORD_SERVER_NAME = ''

X_GRAB_DISCORD_SERVER = 0
Y_GRAB_DISCORD_SERVER = 0
WIDTH_GRAB_DISCORD_SERVER = 0
HEIGH_GRAB_DISCORD_SERVER = 0

X_CLICK_DISCORD_SERVER = 0
Y_CLICK_DISCORD_SERVER = 0

X_ENTER_FIELD = 0
Y_ENTER_FIELD = 0

A1_HSV = 0 
A2_HSV = 0
A3_HSV = 0

B1_HSV = 255
B2_HSV = 100
B3_HSV = 255

